### PR TITLE
Fix State constructor attributes

### LINKED ISSUE #56: Support Android Studio Preview
Is Android Studio layout preview supported? For now if I am using the lib in a screen, AS will present a blank screen. I tried using `tools:initialState="@id/stateContent"` but it did not do much :( .

### PR DESCRIPTION
**Pull request by sjcqs**
Style resource was used instead of attributes resource thus Android Studio was unable to load a preview.
Fixes #56
fix_AS_preview

### CODE REVIEW

File: lib/src/main/java/com/fabernovel/statefullayout/StatefulLayout.kt [hunk 1]
```diff
@@ -142,7 +142,7 @@ class StatefulLayout : FrameLayout, StateContainer<Int, State> {
     }
 
     override fun onViewAdded(child: View?) {
-        super.onViewAdded(child)
```
Comment (flolom) [inline lib/src/main/java/com/fabernovel/statefullayout/StatefulLayout.kt:145]: removing the call to the super method : is it done on purpose ?

Comment (sjcqs) [reply lib/src/main/java/com/fabernovel/statefullayout/StatefulLayout.kt:145]: No it's a mistake
